// zdxresume/src/pages/Err404.vue
<template>
  <div class="co_404">
    <img src="../assets/basicImg/err404.png" alt="">
  </div>
</template>

<script>
export default {

}
</script>

<style lang="less" scoped>
.co_404 {
  position: relative;
  width: 100%;
  height: 100%;
  img {
    width: 300px;
    position: absolute;
    top: 50%;
    left: 50%;
    margin: -90px 0 0 -150px;
  }
}
</style>

// ReactFront/src/pages/Err404.jsx
import React from 'react'
const outCss = {
  position: 'relative',
  height: '100%'
}
const imgCss = {
  position: 'absolute',
  width: '360px',
  top: '50%',
  left: '50%',
  margin: '-180px 0 0 -180px'
}
export default class Err extends React.Component {
  render () {
    return (
      <div style={outCss}>
        <img style={imgCss} src={require('../assets/basicimg/error404.png')} alt=""/>
      </div>
    )
  }
}
